import { Patient } from "../Types";

interface Ward {
  id: number;
  name: string;
  patients: Patient[];
}

export const dummyPatients: Ward[] = [
  {
    id: 1,
    name: "General Ward",
    patients: [
      {
        id: 1,
        name: "Arun Kumar",
        bed: 1,
        gender: "Male",
        age: 45,
        email: "arun.kumar@example.com",
        bloodtype: "A+",
        contact: "98401 12345",
        status: "Occupied",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-10"),
      },
      {
        id: 2,
        name: "Divya Ramesh",
        bed: 2,
        gender: "Female",
        age: 32,
        email: "divya.ramesh@example.com",
        bloodtype: "O+",
        contact: "95000 67890",
        status: "Occupied",
        appointType: "Emergency",
        appointmentDate: new Date("2024-09-12"),
      },
      {
        id: 3,
        name: "Revathi S",
        bed: 3,
        gender: "Female",
        age: 27,
        email: "revathi.s@example.com",
        bloodtype: "B+",
        contact: "93600 12345",
        status: "Billing",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-15"),
      },
      {
        id: 4,
        name: "Manikandan P",
        bed: 4,
        gender: "Male",
        age: 40,
        email: "manikandan.p@example.com",
        bloodtype: "AB-",
        contact: "82200 99887",
        status: "Billing",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-16"),
      },
    ],
  },
  {
    id: 2,
    name: "ICU Ward",
    patients: [
      {
        id: 5,
        name: "Karthik Raj",
        bed: 1,
        gender: "Male",
        age: 50,
        email: "karthik.raj@example.com",
        bloodtype: "A-",
        contact: "90920 11223",
        status: "Occupied",
        appointType: "Emergency",
        appointmentDate: new Date("2024-09-14"),
      },
      {
        id: 6,
        name: "Meena K",
        bed: 2,
        gender: "Female",
        age: 38,
        email: "meena.k@example.com",
        bloodtype: "O-",
        contact: "91500 66778",
        status: "Billing",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-13"),
      },
      {
        id: 7,
        name: "Subramanian A",
        bed: 3,
        gender: "Male",
        age: 60,
        email: "subramanian.a@example.com",
        bloodtype: "B-",
        contact: "97890 33445",
        status: "Billing",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-18"),
      },
    ],
  },
  {
    id: 3,
    name: "Pediatric Ward",
    patients: [
      {
        id: 8,
        name: "Vignesh S",
        bed: 1,
        gender: "Male",
        age: 5,
        email: "vignesh.s@example.com",
        bloodtype: "O+",
        contact: "80120 55667",
        status: "Occupied",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-19"),
      },
      {
        id: 9,
        name: "Anjali B",
        bed: 2,
        gender: "Female",
        age: 8,
        email: "anjali.b@example.com",
        bloodtype: "A+",
        contact: "93455 99887",
        status: "Occupied",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-20"),
      },
      {
        id: 10,
        name: "Rohit N",
        bed: 3,
        gender: "Male",
        age: 7,
        email: "rohit.n@example.com",
        bloodtype: "B+",
        contact: "99620 88990",
        status: "Billing",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-21"),
      },
      {
        id: 11,
        name: "Keerthana V",
        bed: 4,
        gender: "Female",
        age: 6,
        email: "keerthana.v@example.com",
        bloodtype: "AB+",
        contact: "88700 11234",
        status: "Billing",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-22"),
      },
    ],
  },
  {
    id: 4,
    name: "Maternity Ward",
    patients: [
      {
        id: 12,
        name: "Priya M",
        bed: 1,
        gender: "Female",
        age: 30,
        email: "priya.m@example.com",
        bloodtype: "O+",
        contact: "90925 33445",
        status: "Occupied",
        appointType: "Emergency",
        appointmentDate: new Date("2024-09-23"),
      },
      {
        id: 13,
        name: "Anitha R",
        bed: 2,
        gender: "Female",
        age: 28,
        email: "anitha.r@example.com",
        bloodtype: "A+",
        contact: "94444 55566",
        status: "Occupied",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-24"),
      },
      {
        id: 14,
        name: "Baby Lakshmi",
        bed: 3,
        gender: "Female",
        age: 0,
        email: "baby.lakshmi@example.com",
        bloodtype: "B+",
        contact: "90000 11122",
        status: "Billing",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-25"),
      },
    ],
  },
  {
    id: 5,
    name: "Surgical Ward",
    patients: [
      {
        id: 15,
        name: "Sathish R",
        bed: 1,
        gender: "Male",
        age: 40,
        email: "sathish.r@example.com",
        bloodtype: "O-",
        contact: "97890 22334",
        status: "Occupied",
        appointType: "Emergency",
        appointmentDate: new Date("2024-09-26"),
      },
      {
        id: 16,
        name: "Lakshmi Devi",
        bed: 2,
        gender: "Female",
        age: 35,
        email: "lakshmi.devi@example.com",
        bloodtype: "AB+",
        contact: "98405 66778",
        status: "Occupied",
        appointType: "IPD",
        appointmentDate: new Date("2024-09-27"),
      },
      {
        id: 17,
        name: "Mohan K",
        bed: 3,
        gender: "Male",
        age: 45,
        email: "mohan.k@example.com",
        bloodtype: "B-",
        contact: "93600 44322",
        status: "Billing",
        appointType: "OPD",
        appointmentDate: new Date("2024-09-28"),
      },
    ],
  },
];
